


version: "3.8"

services:
  backend:
    build: .  # Dockerfile should be in the root of the project
    container_name: backend-local
    image: faq-backend
    ports:
      - "3000:3000"  # Exposes backend on port 3000
    env_file:
      - .env  # Loads environment variables from .env file
    restart: always
    volumes:
      - .:/app  # Mounts the current directory to the container (optional, for development)
    command: ["npm", "start"]  # Ensure this matches your app's start command if necessary
  

volumes:
  redis_data:
    driver: local  # Specifies the volume for Redis persistence
