
version: "3.8"

services:
  backend:
    build: .
    container_name: backend-local
    ports:
      - "3000:3000"  # Exposes backend on port 3000
    depends_on:
      - redis  # Ensures Redis starts first
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app  # Mounts the current directory to the container (optional)
  
  redis:
    image: redis:latest
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server"]

volumes:
  redis_data:
    driver: local
